esphome:
  name: contactlesswaterlevel

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Contactlesswaterlevel"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: template
    name: "Tank Level"
    unit_of_measurement: "%"
    update_interval: 5s
    icon: "mdi:water"
    lambda: |-
      if (id(water_100).state) {
        return 100; 
      }
      else if (id(water_75).state) {
        return 75;
      }
      else if (id(water_50).state) {
        return 50;
      }
      else if (id(water_25).state) {
        return 25;
      } 
      else {
        return 0;
      }


binary_sensor:
  - platform: gpio
    name: "Water 100"
    id: water_100
    pin:
      number: GPIO14
#      inverted: true
      mode:
        input: true
 #       pullup: true
        
  - platform: gpio
    pin:
      number: GPIO12
#      inverted: true
      mode:
        input: true
 #       pullup: true    
    name: "Water 75"
    id: water_75
#    filters:
#      - delayed_on: 500ms

  - platform: gpio
    pin:
      number: GPIO5
 #     inverted: true
      mode:
        input: true
 #       pullup: true    
    name: "Water 50"
    id: water_50
#    filters:
#      - delayed_on: 500ms

  - platform: gpio
    pin:
      number: GPIO4
#      inverted: true
      mode:
        input: true
  #      pullup: true    
    name: "Water 25"
    id: water_25
#    filters:
#      - delayed_on: 500ms


web_server:
  port: 80